### PR TITLE
ActionSelect: Add component

### PR DESCRIPTION
**Pull request by ItsJonQ**
## ActionSelect: Add component

Screen Recording 2019-05-13 at 11 47 AM_1
(GIF shows interactions with ActionSelect using keyboard)

This update adds a new `ActionSelect` component to HSDS: React! This component renders extends the UI of a SelectDropdown, allowing it to render contextual content within, based on the selected item.

For additional context, check out this screencast!

https://www.loom.com/share/bb315900af704b94844bf850ca833c32

cc'ing @tjbo for implementation review. Check out the Storybook for this component to get an idea of how we'll us it in the app.

cc'ing @digitaldesigner + @ryan-mulrooney  for UI/UX review. Netlify deploy preview coming soon! Will add direct link in comments

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@digitaldesigner  + @ryan-mulrooney 

# Direct link to deploy preview

https://deploy-preview-621--hsds-react.netlify.com/iframe.html?id=actionselect--default

**Comment by ItsJonQ** [comment]
@digitaldesigner You bet!! Thanks for the suggestion! Check it out:

The fade animation timing syncs with the resizing timing. Both can be controlled BTW.

Example of it being slowed down to `3000` (ms)

Screen Recording 2019-05-14 at 09 50 AM

Actual speed (`160`)

Screen Recording 2019-05-14 at 09 51 AM

Bonus! Improved accessibility support (for Dropdowns as a whole).
Added an announcer to declare when the menu is opened/closed (with ability to provide custom label). And also for screen reader to be aware of option count (e.g. `Open Beacon (2/3)`)

Screen Recording 2019-05-14 at 09 18 AM

**Comment by ItsJonQ** [comment]
🍐 'ed with @ryan-mulrooney . Discussed some UX improvements for this component. The main one being visual clarity for when the Select is open. We tried this idea, where we fade the content a bit when it's open.

Screen Recording 2019-05-14 at 11 59 AM


Screen Shot 2019-05-14 at 11 59 05 AM

**Comment by ItsJonQ** [comment]
From @ryan-mulrooney 

> 👏 
> beautiful homie

**Comment by ItsJonQ** [comment]
Will merge this up and release!! We can definitely iterate if needed 💪

**Comment by digitaldesigner** [comment]
Oh wow yeah these are great enhancements. Thanks @ItsJonQ and @ryan-mulrooney

**Pull request merged**
