### PR TITLE
Add Depth to components

### PR DESCRIPTION
**Pull request by tinkertrain**
# Feature

Use the new Depth mixins in HSDS components:

d200 - FluffyCard
d300 - Page
d300 - RadioCard
d400 - CheckmarkCard
d400 - ArticleCard
d400 - Attachment with preview
d600 - Notification
d600 - MessageCard
d700 - Modal

### CODE REVIEW

**Comment by tinkertrain** [comment]
Hi @digitaldesigner, a couple of questions for ya!

## CheckmarkCard 
* I put the same depth as -> RadioCard, is that ok? should I roll back those?
* Just noticed that the focus style on a checked card is invisible as the border and the focus style are the same

## Other components
Should we apply depth to any of these?
* AttachmentList with preview
* MessageCard

**Review by digitaldesigner — CHANGES_REQUESTED** [review]
Ah sorry man, CheckmarkCard should be `d400`

If you want to apply depth to AttachmentList with preview then it'd be `d400`, and MessageCard is `d600`

**Comment by tinkertrain** [comment]
> Ah sorry man, CheckmarkCard should be `d400`
> 
> If you want to apply depth to AttachmentList with preview then it'd be `d400`, and MessageCard is `d600`

Thanks! I made the updates

**Review by digitaldesigner — APPROVED** [review]
Looks great, thanks @tinkertrain

**Review by plbabin — APPROVED** [review]
looks good 🚀

**Pull request merged**
