### PR TITLE
Testing: Add Cypress!

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Testing: Add Cypress!

This update adds Cypress to HSDS: React!! Cypress has been set up to
run automatically against the project's Storybook in CI. At the moment,
there's only one test (for Button).

### Cypress

Cypress tests can be run manually like:

```
npm run test:cy
```

This fires up storybook + runs the Cypress suite.

Otherwise, cypress can be run via:

```
npm run cy:run
```

### propConnect updates

`propConnect` has been enhanced to automatically provide a `data-cy` HTML
attribute for connected components. This ensures that any prop wrapped
components will have some sort of unique `data-cy` identifier. Coverage
for this will improve as we continue to refactor older components with
`propConnect`.

Lastly, various `propConnect` namespaces have been updated to remove any `.`. The period makes both Enzyme and Cypress tests unhappy for selector targeting.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
Oh poo. Netlify is choking at Cypress downloads.

**Comment by ryan-mulrooney** [comment]
> Oh poo. Netlify is choking at Cypress downloads.

Is this an insurmountable problem? :)

**Comment by ItsJonQ** [comment]
@ryan-mulrooney It's been resolved! I've added an environment variable to help optimize Netlify a bit. Also! Netlify caches dependencies.. so subsequent builds should be really fast. Like approx 1 min fast :)

**Comment by ItsJonQ** [comment]
Test failed. `babel-core` issues with Travis + `node_modules`. Clearing cache and trying again

**Comment by ItsJonQ** [comment]
🙌 awwwwww yiss!

**Pull request merged**
