### PR TITLE
Add Nav component

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Add Nav component

screen recording 2019-02-26 at 04 13 pm

(GIF: Link `Four` is disabled)

This update adds a new `Nav` component, which can be used to construct a nav bar within the application.

Still WIP.

* [x] Write tests
* [x] Write docs
* [x] Create Toolbar integration example

### CODE REVIEW

**Comment by ItsJonQ** [comment]
## Demo URL

https://deploy-preview-503--hsds-react.netlify.com/?selectedKind=Nav&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by digitaldesigner** [comment]
Perfect! You even got the little rounded bar locked in, great 👁

**Comment by ItsJonQ** [comment]
@digitaldesigner Haha, I do what I can 😉 

Cool! In that case, it's just documentation + testing that's left

**Comment by ItsJonQ** [comment]
cc'ing @ryan-mulrooney for QA review

**Comment by ryan-mulrooney** [comment]
@ItsJonQ Would you be able to add some knobs for me to tinker with it please? Namely, to be able to add some text and remove the `i` icon.

**Comment by ItsJonQ** [comment]
@ryan-mulrooney Sure thing :)

**Comment by ItsJonQ** [comment]
@ryan-mulrooney 🙌 

screen shot 2019-03-01 at 3 58 24 pm

**Comment by ryan-mulrooney** [comment]
@ItsJonQ u da man

**Comment by ryan-mulrooney** [comment]
@ItsJonQ Love it. Looks great.

**Comment by ItsJonQ** [comment]
@ryan-mulrooney 

> `data-cy='main-nav-item'` to each item
That would be done within `hs-app`

Defo can add `data-cy` to the error icon though!

**Comment by ryan-mulrooney** [comment]
> @ryan-mulrooney
> 
> > `data-cy='main-nav-item'` to each item
> > That would be done within `hs-app`
> 
> Defo can add `data-cy` to the error icon though!

Oh, interesting. How come one in hs-app one in HSDS? Maxi also added `data-cy` attrs to each part of his component in HSDS

**Comment by ItsJonQ** [comment]
@ryan-mulrooney 

> I suppose because the Nav is generic

Bingo!! :D

**Comment by ItsJonQ** [comment]
Chatted with @ryan-mulrooney . We have a 👍 for this!

**Pull request merged**
