### PR TITLE
HSDS-256: Microsurveys: MultipleChoiceSurvey Component

### PR DESCRIPTION
**Pull request by jakubjanczyk**
# Problem/Feature
This PR adds new variant for Messages Microsurveys type: Multiple Choice.
This component is quite simple, it takes list of choices as input prop and renders as many Radio buttons as there are choices. Other standard mechanisms from previous microsurvey components are used without any modifications.

This can be checked in by going to Storybook - there is new Story under `MessageCard` added with some example data.

Screenshot from 2022-05-16 17-40-37

Screenshot from 2022-05-16 17-40-52

Write to your heart's content, include:

- [ ] A link to the Figma design in your story (list regularly updated [here](https://docs.google.com/spreadsheets/d/19-5gNbYuKjOb-kk7VTQZ0i_VWVd_8lubx-uhrlPUu1E/edit#gid=0))
- [ ] A link to the Story(ies) in the description
- [ ] Is there a Jira ticket associated?
- [ ] If useful, add screenshots or videos
- [ ] If useful (and unclear), add a little explanation of why a certain path was taken
- [ ] Instructions on how to test
- [ ] Found any restrictions/limitations? Let us know!

## Guidelines

Make sure the pull request:

- [ ] Follows the established folder/file structure
- [ ] Adds unit tests
- [ ] If it is a refactor or change to an existing component, have you verified it won't break existing Cypress tests or have you updated them?
- [ ] Did you verify some accessibility (a11y) basics?
- [ ] Adds/updates stories. [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-4-writing-stories--page)
- [ ] Adds/updates documentation (ie `proptypes`) [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-3-writing-components--page)
- [ ] Has it been tested in [Help Scout's supported browsers](https://docs.helpscout.com/article/1292-supported-browsers-and-system-requirements)?
- [ ] Requests review from designer of the feature
- [ ] Add label (bug? feature?)

### CODE REVIEW

**Comment by alexestrada** [comment]
@jakubjanczyk thanks! A few things on this one: 

- The font for the options should be SF Pro @ 14px, that is 100% my mistake! _:sorry:_ 
- I'd like to honor the spacing set in the design to give the items a little more breathing room. I understand that's our component, but since it's technically a "white-label" message, it's ok if we aren't using our exact HS UI. 
- If we're going to go with blue selection over matching the Beacon color, the current radio selection feels really... bold! We have a different design in Figma than what's in Storybook 🤔  I'd like to get a few more eyes on this one and see if it's worth doing something different specifically for these messages.

**Review by tinkertrain — APPROVED** [review]
Code and functionality looks good to me 💯

**Comment by jakubjanczyk** [comment]
@alexestrada Just one thing - we are not using `SF Pro` font anywhere in our code (neither HSDS, hs-app or beacon). Do we want to start using it here? If so, we'll need to start loading it everywhere :)

I'll wait for the decision about the blue radio :)

**Comment by alexestrada** [comment]
@jakubjanczyk just to capture what we've chatted about: 

- Font is just defaulting system fonts (SF Pro is just what we use in Figma to denote that)
- Radio button color and focus state to change to `Charcoal 300`

**Review by tinkertrain — APPROVED** [review]
:shipit:

**Pull request merged**
