### PR TITLE
BEMBED-338: Performance improvements for beacon

### PR DESCRIPTION
**Pull request by jakubjanczyk**
# Problem/Feature

This PR contains any changes that are necessary to improve on performance/bundle size for Beacon. Full list TBD

Write to your heart's content, include:

- [ ] A link to the Figma design in your story (list regularly updated [here](https://docs.google.com/spreadsheets/d/19-5gNbYuKjOb-kk7VTQZ0i_VWVd_8lubx-uhrlPUu1E/edit#gid=0))
- [ ] A link to the Story(ies) in the description
- [ ] Is there a Jira ticket associated?
- [ ] If useful, add screenshots or videos
- [ ] If useful (and unclear), add a little explanation of why a certain path was taken
- [ ] Instructions on how to test
- [ ] Found any restrictions/limitations? Let us know!

## Guidelines

Make sure the pull request:

- [ ] Follows the established folder/file structure
- [ ] Adds unit tests
- [ ] If it is a refactor or change to an existing component, have you verified it won't break existing Cypress tests or have you updated them?
- [ ] Did you verify some accessibility (a11y) basics?
- [ ] Adds/updates stories. [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-4-writing-stories--page)
- [ ] Adds/updates documentation (ie `proptypes`) [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-3-writing-components--page)
- [ ] Has it been tested in [Help Scout's supported browsers](https://docs.helpscout.com/article/1292-supported-browsers-and-system-requirements)?
- [ ] Requests review from designer of the feature
- [ ] Add label (bug? feature?)

### CODE REVIEW

**Comment by jakubjanczyk** [comment]
@Charca I am thinking if at this stage there is anything else we need to change in hsds-react? The only thing I thought about was to extract `makeBrandColors` to its own file, because we use it in critical path and the file that contains it adds around 3-5 kB of unused code (including `lodash.get` dependency). However, maybe at this point we are good enough with what we have and there is no point in complicating the code (and we will have this problem sorted out when hsds would be fully tree shakeable in the future :smile: :crossed_fingers:)

**Comment by Charca** [comment]
@jakubjanczyk yep this looks good to me, I'm not planning to make any other changes for now!

**Comment by jakubjanczyk** [comment]
@tinkertrain If I could please get your eyes on this one before I make a final release :)

**Review by tinkertrain — APPROVED** [review]
With hsds4, tree shaking should be much better! 🤞

**Pull request merged**
