### PR TITLE
Fix HelpText state and add stories

### PR DESCRIPTION
**Pull request by tompedals**
## Fix HelpText state and add stories

The `state` prop of `HelpText` was not being respected and it was always using the `faint` text style. This PR moves the state styling to the child `Text` component rather than adding styles to the `HelpText` component as they were are not specific enough.

screen shot 2018-12-03 at 19 05 36
screen shot 2018-12-03 at 19 05 31
screen shot 2018-12-03 at 19 05 27

I added a story to test these changes.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@tompedals Gonna help fix tests

**Comment by tompedals** [comment]
@ItsJonQ I'm just looking at the tests now

**Comment by ItsJonQ** [comment]
@tompedals Looks like we just need to add `state && `is-${state}`,  back into the `classNames()` :).
Even thought it's not used to render styles, its' handy to have it in the classNames for `querySelector` or inspect element purposes

**Comment by tompedals** [comment]
I need to rework this solution slightly, it doesn't work when passing in child components and not just a string.

**Comment by tompedals** [comment]
@ItsJonQ I've updated the fix now so we keep the state styles on the `HelpText` component too for when we don't have string children. It wouldn't quite work if we have `<HelpText state="error"><Text>Something</Text></HelpText>` as the `Text` would still override the error state styles, but I think that is acceptable as we would just pass the string value usually instead.

**Comment by ItsJonQ** [comment]
@tompedals Sounds good to me! Thank you!!!

**Pull request merged**
