### PR TITLE
Update NodeJS version to 16

### PR DESCRIPTION
**Pull request by jakubjanczyk**
# Problem/Feature
Node v12 is reaching EOL in April, so we want to update to the latest active version (v16). There is no impact to the end users, as Node is used only for building the project.

To test: checkout the branch and check that npm scripts are working (`build`, `start`, `test`, etc). Use `nvm use` to switch to node 16 :)

This PR is part of this task: https://helpscout.atlassian.net/browse/JS-218

## Guidelines

Make sure the pull request:

- [ ] Follows the established folder/file structure
- [ ] Adds unit tests
- [ ] If it is a refactor or change to an existing component, have you verified it won't break existing Cypress tests or have you updated them?
- [ ] Did you verify some accessibility (a11y) basics?
- [ ] Adds/updates stories. [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-4-writing-stories--page)
- [ ] Adds/updates documentation (ie `proptypes`) [Guidelines](https://hsds.helpscout.com/?path=/docs/%F0%9F%8F%A0-welcome-3-writing-components--page)
- [ ] Has it been tested in [Help Scout's supported browsers](https://docs.helpscout.com/article/1292-supported-browsers-and-system-requirements)?
- [ ] Requests review from designer of the feature
- [ ] Add label (bug? feature?)

### CODE REVIEW

**Comment by justinwolfe** [comment]
FYI, I was trying to do a release today and [ran into some trouble](https://helpscout.slack.com/archives/CA5RH7QUC/p1647900920825699). I'm now on Node 16 and when I was trying to run releases using that, I was getting this `403` from Node when trying to publish the package and had to temporarily switch back to 12 to be able to publish

May not be an issue once this PR is in and the project is also on Node 16, but wanted to flag as something worth testing!

**Comment by jakubjanczyk** [comment]
@justinwolfe Thanks for the information and sorry for the trouble :( 
I was able to successfully publish beta release from this branch (however I've run into some other issue, but was able to resolve it) and I believe the issue you are seeing is related to one of:
- there is related to the fix I have applied (`npm publish` has changed in newest npm and there was a need to slightly update the script, see the latest commit)
- I see people having the same error when they don't have email verified on npm. Could you check if yours is? I think if you open your account you should have information if it isn't

**Comment by justinwolfe** [comment]
@jakubjanczyk No worries at all—it's awesome that you're doing this. Yep, can confirm my NPM email address is verified, so I bet it was the first thing. Awesome that you've got a fix in!!! 🙌

**Review by tinkertrain — APPROVED** [review]
Thanks for the hard work making sure this works... 🚢 !

**Pull request merged**
