### PR TITLE
Improve Tag UI. Add tag size, tag new color and a TagList clear all button

### PR DESCRIPTION
**Pull request by plbabin**
This update improve the overall UI of the tag component to match `HSDS-product`. It improves the font, the remove icon and the padding of the component.

**Before**
Image 2019-04-18 at 11 45 15 AM

**After**
Image 2019-04-18 at 11 45 25 AM

### New color and size
The update add a new filled color to the Tag component as well as a new size (sm & md)
Image 2019-04-18 at 1 41 22 PM

### TagList clearAll and showAll
This update add the possibility to show all tags instead of just two lines. We also add a `clearAll` prop that will show a button to remove all tags from the list. The clearAll button will be visible only if there is 2 or more tags in the list

Screen Recording 2019-04-18 at 12 37 PM

### CODE REVIEW

**Comment by plbabin** [comment]
@ItsJonQ latest commit fixed the issue. I merged the new spinner PR in this one, and adjust some alignments

**Comment by plbabin** [comment]
I added a size prop to `TagList` so we can set the spacing between each tag

**Comment by plbabin** [comment]
I updated the component with Flexy grid

For the font-size, I went with `11px` because that's the current value in sketch. If it's a case of real life that needs to be different compare with Sketch, I can totally update the font-size. cc @jaredmcdaniel

**Comment by ItsJonQ** [comment]
@plbabin Will take care of merge conflict :D

**Comment by jaredmcdaniel** [comment]
Chatted through a couple minor tweaks with @plbabin in Slack. But the main ones being we'll go back to `12px` font size for the tags (and will update in HSDS). Also updating `Clear all` text to be `12px` for better consistency.

Lastly, just pointing out Im still seeing some issues with the truncation/ellipse issue that @ItsJonQ pointed out above.

**Comment by ItsJonQ** [comment]
Will merge/release on green

**Pull request merged**
