### PR TITLE
Page Component: Update Responsive Styles

### PR DESCRIPTION
**Pull request by knicklabs**
This update changes the breakpoints for the max-width and the changes the padding applied at different breakpoints. 

The width is constrained until 1050px (previously 1000px).

Beyond the default padding (y: 50px, x: 50px), we introduced:

Wide Screen: 1050 - 1350 (y: 50px, x: 100px)

Super Wide Screen: 1350 - 1450 (y: 65px, x: 50px)

Full Screen: 1450+ (y: 65px, x: 100px)

I'll update this with a link to the Story after Storybook rebuilds.

See: https://github.com/helpscout/hsds-product-ui/wiki/Responsive

### CODE REVIEW

**Comment by knicklabs** [comment]
Here's a link to the specific story for the new breakpoints: https://deploy-preview-492--hsds-react.netlify.com/?selectedKind=Page%2FExample&selectedStory=Responsive&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by jaredmcdaniel** [comment]
@knicklabs This might be another one of those "this is just a Storybook thing" things ... but wanted to ask:

The default block size should be 700px. Its currently 680 though I see in the styles `max-width: 700px` is set. 🤔 



As a result, form label and content widths are off. Currently `480px`, should be `500px`.

**Comment by ItsJonQ** [comment]
@jaredmcdaniel I fixed up the Story for the responsive Page component. It should behave much more like it's implementation within hs-app now.

Pro tip! for Storybook, add `iframe.html` in the URL to see the dedicated story (without the other stuff):

https://deploy-preview-492--hsds-react.netlify.com/iframe.html?selectedKind=Page%2FExample&selectedStory=Responsive&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by ItsJonQ** [comment]
Ugh.. really need to fix these long Netlify build times

**Comment by jaredmcdaniel** [comment]
Looking much better now! 👏 

Only thing I noticed is it looks like we're missing breakpoints for `06. Widest`. Specifically with the width of the form column. At > 1650px, it should be 650px vs 500px ... making the block container 1200px.

**Comment by ItsJonQ** [comment]
@jaredmcdaniel Haii!! I added the adjustments for the `widest` breakpoint.
screen recording 2019-02-22 at 09 27 am

**Comment by ItsJonQ** [comment]
Awesome!! Merging this up

**Pull request merged**
