### PR TITLE
Add RateAction Component

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Add RateAction Component

screen recording 2019-02-04 at 01 52 pm

This update adds a new `RateAction` (button) component, which enhances the rating interaction visualized with `Emoticon`.

`Emoticon` has been refactored with the latest HSDS conventions, and adjusted to accommodate the interactions with `RateAction`.

### Review

cc'ing @digitaldesigner for design/interaction review :)

**Preview URL** 👇
https://deploy-preview-465--hsds-react.netlify.com/?selectedKind=RateAction&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

The animations and styles were plucked + refactored from:
https://docs.helpscout.com/article/1208-migrating-to-mailbox-api-2-0

### Todo

Add tests + docs

### CODE REVIEW

**Comment by ItsJonQ** [comment]
https://dribbble.com/shots/5590467-Having-fun-with-ratings

**Comment by ItsJonQ** [comment]
@digitaldesigner Yayyyyy

screen recording 2019-02-06 at 02 39 pm

https://deploy-preview-465--hsds-react.netlify.com/?selectedKind=RateAction&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by ItsJonQ** [comment]
@digitaldesigner Ready for re-review + QA :)

**Comment by digitaldesigner** [comment]
Looks great to me @ItsJonQ — only question is whether we want to include the margin between the two icons within the component? If so, it should be 5px. Great work man

**Pull request merged**
