### PR TITLE
Table: Updates styles to latest (header row)

### PR DESCRIPTION
**Pull request by tinkertrain**
Some updates to the styles have been requested, mostly regarding the Header Row:

image

## Solution

Most of the changes will just happen but we did add a couple of convenience things:

1. `renderHeaderCell` has always been available to render icons (or whatever), since icons can be a common occurrence and to avoid each developer having to implement the right styles, you can now pass an object with a key `iconName`, and that's it:
```js
// example column
{
          title: 'Company',
          columnKey: 'companyName',
          align: 'center',
          width: '35%',
          renderHeaderCell: { iconName: 'chat' },
          sorter: this.sortAlphabetically,
},
```
2. Previously, if the table was sortable and `renderHeaderCell` was passed, the markup was incorrect, this is fixed now.
3. If the table is sortable, it gets the class name: `is-sortable` 
4. Removes the Table Cell memoization, as mentioned [here](https://github.com/helpscout/hs-app-ui/pull/191#discussion_r744992183)
5. The Icon title was not being displayed, moved it up a level in the markup

## Stories

The [`Table` stories](https://deploy-preview-999--hsds-react.netlify.app/?path=/story/components-structural-table--with-sorting) reflect the changes

## Screenshots

Icon header cell (hover):
Screen Shot 2021-11-11 at 2 47 22 PM

Icon header cell (sorted):
Screen Shot 2021-11-11 at 2 47 42 PM

Regular text header cell (hover):
Screen Shot 2021-11-11 at 2 48 09 PM

Regular text header cell (sorted):
Screen Shot 2021-11-11 at 2 47 51 PM

Table with border on header row (normal height):
Screen Shot 2021-11-11 at 2 48 21 PM

Custom header row height:
Screen Shot 2021-11-11 at 2 49 00 PM

### CODE REVIEW

**Comment by tinkertrain** [comment]
@cen10 FYI this PR removes the memoization, hopefully that fixes your issues, when and if it becomes an issue perf wise, we'll look at it again 👍

**Comment by digitaldesigner** [comment]
Wow awesome work on this mate, I had a couple requests:

- Increase `font-weight` to `500`
- Icon seems to be sized down, should be `24x24`
- Add `+1px` padding top and bottom of all shapes to make the whole thing 2px taller
- Reduce the margin between the chevron and edge of the shape by `-2px` (one of those weird optical alignment things)

**Comment by digitaldesigner** [comment]
Throwing this one to @jaredmcdaniel for review whilst I'm out 🌴

**Comment by tinkertrain** [comment]
@digitaldesigner Thanks! Hopefully I got all what you said:

Screen Shot 2021-11-12 at 11 47 40 AM

**Comment by cen10** [comment]
@digitaldesigner @tinkertrain FYI, I have a PR open that PL would like me to hold off on merging until this update hits, and I'm supposed to have my work go through QA and deployed by Thursday if possible. I'd like Malika to QA it with the new styles. It's not the end of the world if it takes longer, but if you have the space to make time for this sooner rather than later I'd appreciate it.

**Comment by cen10** [comment]
@jaredmcdaniel I just noticed that Buzz tagged you on this while he's out - if you have time to look at this I'd appreciate it as it's a blocker for me! :)

**Comment by jaredmcdaniel** [comment]
Sorry I couldn't get to this last week! Visuals look good from my end ... just a couple things to confirm UX-wise:

Looking at the [`with Sorting` story](https://deploy-preview-999--hsds-react.netlify.app/?path=/story/components-structural-table--with-sorting) ... I noticed that clicking in the header area (not on the label itself) will also toggle the column sorting. Is that expected? 
CleanShot 2021-11-15 at 12 31 28


Also, when sorting by `Customer (sorts by company)`, the thread count icon header also updates to the sorted state. I'm assuming there should be only 1 active/sorted state at a time.

image

**Comment by tinkertrain** [comment]
Thanks @jaredmcdaniel for looking at this!

1. I moved the click area to be the actual label, thanks for noticing this 👍 
2. In this particular example that is expected, is not very clear because I changed the label to the 'chat' icon to showcase those styles, but the column is "company" and the table detects that both that one and the "Customer (sorts by company)" get sorted by company, so it displays it that way (you can see that both columns are equally sorted)

**Comment by jaredmcdaniel** [comment]
Thanks @tinkertrain! I'm on my phone and can't see how to approve the PR from the GH app, but good to go from my end! 👍

**Pull request merged**
